### ISSUE TITLE
Error when trying to login/register

### ISSUE THREAD

**Issue by Y-Taras** [kenrogers/beer-buddies#1]
Can't find out why I'm getting an error when I try to register
[
![screenshot from 2017-03-18 11 22 36](https://cloud.githubusercontent.com/assets/8538134/24070827/448dc812-0bcd-11e7-8fbf-e67a42222825.png)
]. So here's  what I've done:
1) ` git clone https://github.com/kenrogers/beer-buddies.git`
2) `cd beer-buddies` and `meteor npm install`
3) `meteor`
Then in browser I go to http://localhost:3000, fill and submit a form and got an error as on the screenshot.
BTW Since React-router v4 is now latest stable version - It would be good if you mentioned in tutorial that you are using React-router v3.

**Comment by productiveme** [comment]
I got a similar error on logging in / creating a user, but it was a simple mistake, trying to evaluate `error.reason` when `error` is undefined, I just added an additional test (loginRegistration.jsx:17) to move on...

```
if (error && error.reason === 'Email already exists.') { ... }
```

**Comment by h2s20** [comment]
I also told Ken about the bug some weeks ago and he responded that he will fix it but he hasn't fixed it yet.

**Comment by kenrogers** [comment]
Luckily my laziness/forgetfulness was resolved by @productiveme I merged his fix into the master branch. Sorry I've been so late on all this. Book is back in full swing and being actively worked on now for Meteor 1.5.
