### ISSUE TITLE
method not found error

### ISSUE THREAD

**Issue by crippledjosh** [kenrogers/beer-buddies#3]
You're not importing the methods on the server side, I can see it looks like you've got the correct imports in your imports/startup/server, but that file is never imported by your top level server/main.js

Hope that helps and that it's not me that's missing something and being condescending.

**Comment by kenrogers** [comment]
Sorry this has taken me so long, thanks for the issue report, not condescending at all! Sometimes I miss obvious stuff and need other people to point it out for me :) Anyway, this should be fixed now
